module DataInfo
{
    typedef sequence<unsigned long long> ID_LIST; 
    enum TYPE {
        GET,
        SET
    };
    struct Request
    {
        DataInfo::ID_LIST id_list;
        TYPE type;
        string msg;
    };
    #pragma keylist Request type
    // it seems like we can't use unbounded array as keylist
    // RMT_TODO: I need to know what keylist means.
    //#pragma keylist Request id_list
    struct Reply
    {
        unsigned long long deviceID;
        TYPE type;
        string msg;
    };
    #pragma keylist Reply deviceID
};