module DataInfo
{
    typedef sequence<unsigned long long> ID_LIST; 
    typedef sequence<octet> BINARY;
    enum TYPE {
        GET,
        SET,
        SET_SAME_VALUE,
        IMPORT,
        EXPORT
    };
    struct Request
    {
        DataInfo::ID_LIST id_list;
        TYPE type;
        unsigned long long random_seq;
        string msg;
        DataInfo::BINARY binary;
    };
    #pragma keylist Request random_seq
    struct Reply
    {
        unsigned long long deviceID;
        TYPE type;
        unsigned long long random_seq;
        string msg;
        DataInfo::BINARY binary;
    };
    #pragma keylist Reply random_seq
};