name: release

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install necessary packages
        run: sudo apt-get install libcunit1-dev uncrustify libnm-dev libyaml-cpp-dev
      - name: Build
        working-directory: ./
        run: cmake -Bbuild -H. -DBUILD_AGENT=off -DCMAKE_BUILD_TYPE=Release && cmake --build build
      - name: Packages
        working-directory: ./
        run: cmake --build build --target package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}